language: python
sudo: required
dist: xenial
python: 3.7.0
install:
- pip install pipenv
- pipenv install
script:
- pipenv run pytest
notifications:
  slack:
    secure: vl8ew/+M64Eih7YrIma1ADsfTqnrrmvR0rangSIqattIjH4GfPuTGYFyQsarsenRrJW6cr6+DdrP35YmWEfQTUYL3wAbGCiJzNEM9YBdz2XhpCvOJHsn5K9QkXciHjw1AatgxIlk3+JdgkjGEOJWrJ+34jT8x4h4tIZHhU/Y9T3QIshSngW0l1lBXPC4A0y/OTGJA8lk44nplejmM9uBxsO/fXf9doWpAovoYYEKYVA1HDzTsKkNr+NBoLAndJ4zG+d4gIdVJoQKecgywdVCOlpl/SWqFihoOfZz5ENhLJsvW0kevnntoXFki04ee+D28fI+MqCU86pAQF+Zhsq0KG9i4XlDmD+5huLgCTaRN0fALJwLasbRIvDtDdawOjotpqhzUKgPOLDApGw+6v2huWkVkROrpcfMsUnwWdbjiHtt/IAPXbjfEBLX49kGu2dO3M2rLwgi8epEN3GbLJJmSumf7P6gNp/NqjzzealSb3a5v8gZJHwpZcB5u0w8hmjluoaIsPSb+tf0A3P1hqh7NAFON/HFXlD3LUy3aiFETLmKE0ZRBGzPkZCE8qJBmDuMqf8RuH5Fl5Hm9afCUcSoWfdRZj6FrWI3hiY4xRFFSJMWaM7chFRKotTTGeXPjbPsArB+CR4qzQEwTYseytaKA16EJ1c26HHWn23ygfGKhEI=
