version: '3.4'

services:

    db:
        build:
            context: ./config/postgres
            dockerfile: Dockerfile.dev
        container_name: db
        env_file:
            - config/postgres/postgres.env
        volumes:
            - ./config/postgres/data:/var/lib/postgres/data
        ports:
            - "5432:5432"

    expungeservice:
        build:
            context: ./src/backend/expungeservice
            dockerfile: Dockerfile.dev
        container_name: expungeservice
        env_file:
            - config/expungeservice/expungeservice.env
        volumes:
            - ./src/backend/expungeservice:/var/www/expungeservice
            - ./src/backend/tests:/var/www/tests
        ports:
            - "5000:5000"


    webserver:
        build:
            context: ./src/frontend
        container_name: webserver
        volumes:
            - ./src/frontend/src:/usr/src/app/src
        ports:
            - "3000:3000"

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./config/nginx/recordexpunge-nginx.dev.conf:/etc/nginx/conf.d/default.conf
